Strain.create(name:"Cabernet Sauvignon")
Strain.create(name:"Carmenere")
Strain.create(name:"Cabernet Franc")
Strain.create(name:"Malbec")
Strain.create(name:"Merlot")
Strain.create(name:"Petit Verdot")
Strain.create(name:"Sauvignon Blanc")
Strain.create(name:"Chardonnay")
Strain.create(name:"Chenin Blanc")
Strain.create(name:"Muscat")