MagazineOenologist.create(magazine_id: 1, oenologist_id: 2, title: "Editor")
MagazineOenologist.create(magazine_id: 2, oenologist_id: 1, title: "Writer")
MagazineOenologist.create(magazine_id: 3, oenologist_id: 4, title: "Reviewer")
MagazineOenologist.create(magazine_id: 3, oenologist_id: 3, title: "Editor")
MagazineOenologist.create(magazine_id: 1, oenologist_id: 4, title: "Reviewer")